# Generated by Django 3.0.7 on 2020-06-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('marital_status', models.IntegerField(choices=[(0, 'Married'), (1, 'Not married')], default=1)),
                ('married_with', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('nationality', models.CharField(max_length=255)),
                ('color_of_eyes', models.CharField(max_length=255)),
                ('living_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.PersonsAddress')),
            ],
        ),
        migrations.CreateModel(
            name='BorderCrossing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_border_cross', models.DateTimeField(auto_now_add=True)),
                ('border_cross_type', models.IntegerField(choices=[(0, 'In'), (1, 'Out')], default=0)),
                ('allowed_pass', models.BooleanField(default=False)),
                ('forbidden_stuff_withdrawn', models.ManyToManyField(to='person.ForbiddenStaff')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_crosses', to='person.Person')),
            ],
        ),
    ]
